language: java
install: 
  - mvn clean install -DskipTests=true -B -P openshift
deploy:
  - provider: releases
    api-key:
      secure: RQZitfoBm2ICLJovBDW1efW9eTHlw668UW8wHJBMEJwh7MkdT9R76Y8Ki1TysiyFy7TIXaavqQ6+StT5QTNB7zajeqrZgRxKYrs7Pumh8E7Kvad13Ee5CAwCASEpb/HHzHW+tL1SHSt+5DrEIZgLM9wWglK0zOtT8RitNpnw/hWf/UM0PXQfgh2MNUlOz6n9KB9TXolD9qdTKV2n/bBWzyoMLno0e3LTUDqtzfm4X/Rd4euoiy04EMHBxDooTNDhw5Vq8RLNC0FcWiz8+GfTb4tc6wt2vzp5OT77Y1WMz6Ysrd+8f4Yeod8+8/kS9NcrUEE4yir8d5OHwGVfbJ91hoMKb2ZXC86pPXQZLKRw50IGql3laI9JT1+slsKc0esmyy6AMIfkSSzLmkNHUv8NzlUJ/Kw0e+cGAkrhks2AzQnGioHxUCNGeRztNfZYqvtaLjibvRZLOZvn802elO9lGuGTo46if3OCscLAtiecWBfy5/kr4ksI3WbVtBmZSuaKK10sjXAvj/Bd9UJj3q1vuOnuT2Fszc7HmRtORPpuLEZyJjBxD9400yG17/uRMGi0d+7zzlLbqOZaHQnKccvq2/2IVW198Y8p/yT+cOQrvdXIc/edNB603BILp8/TA+taF+2iTq+i+fDh9HFPNFwaf0+Dv3NSFQLEYB9eSWaSXG0=
    skip_cleanup: true	
    file: target/Budget.tar.gz
    on:
      repo: vzwingma/gestion-budget
      tags: true
  - provider: openshift
    user: vincent.zwingmann@gmail.com
    password:
      secure: BzIe6tblw7mExxITI+WMVD2g2ptsYtxZ/Qa8SvV82a7T6NoRInkf5MRKGtC6C8iucfofRo0pDV8frtG8Y5qhNVIVdUNix73mU0r/sWajKTaCZmDcqf2iHvngualZf7cxL+2T8Mx5o0zq7OzM4aTbNVxPZPOcU9YWuL7fJv/iLZe3H013dCp8NQh+eDWK/2Uzfkw9X46d2iQ5lvej9kIEEn2T9pY54vhd3xezJzc4d/6+HM/wSeKmbJfS8fgGwljdftrZwm6frXzXKw3jSKUiakmuG5OC0ssSQgjK4TcS0SERn/EWOf97Vu04gdDATz42KYooS0WWggw6CTyNj+DLUzMahUDaRKKtCb3fNdETp01Rl/J/RTvyDE0Szq5enoPZ6eKsQ19JfxDxLylW7BCq2PGaA7MocNTQ7PP/vY12c6josIOTE5dXayE+OL0tlcHZaQ+5962VNG546mSWVe68y7+d7LSiy4mTR9RG8JXMiZIQPLmp5OQdYLi63mcJV2mpHOPPc8EUrC6zZKfoVR7U3i6AQ+PlqWCfN94UuPfVHpjpcz/sAusU2af6omeRefwyInRXye51SNcK9cueY6ucznyd2vFetcuHVvHru+nBcl2gKcuGaw9+D0ENFUfJc3iPUBVqzv7/I36cabmKrVJY69UzUiRnjhSsCg7f85fpmn4=
    app: budgetdev
    domain: tushkanyogik
    on:
      repo: vzwingma/gestion-budget	