sudo: required
language: java
services:
  - docker
cache:
  directories:
    - $HOME/.m2
git:
  depth: false
# Notification SLACK
notifications:
  slack: terrier-zed:kAeyPHQkcJ1BNDnVZs9W3K3y
before_install:
# Version tagguée > Application de la version sur Maven
  - if [[ $TRAVIS_BRANCH == v* ]]; 
    then 
        VERSION=$(echo $TRAVIS_BRANCH | cut -b 2-); 
    else 
        VERSION=`mvn -q -N org.codehaus.mojo:exec-maven-plugin:exec  -Dexec.executable='echo' -Dexec.args='${project.version}'` ; 
        VERSION=$(echo $VERSION | sed -r 's/(-SNAPSHOT)+//gi')-SNAPSHOT; 
    fi; 
    echo "Application de la version $VERSION"; 
    mvn versions:set -DnewVersion=$VERSION; 
    mvn versions:commit;
install: 
  - mvn clean install sonar:sonar -B -Dsonar.host.url=$SONAR_HOST -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=$SONAR_ORG -Dsonar.projectKey=gestion-budget-communs
#  - mvn clean install -B
  
script:
  # Tag de snapshot. C'est un tag pour permettre le déploiement sur GitHUB.
  - if [ ${TRAVIS_BRANCH} = "master" ]; 
    then 
      echo "ReTag de snapshot"; 
      git tag -d snapshot; 
      git push https://$GITHUB_API_KEY@github.com/vzwingma/gestion-budget-communs :refs/tags/snapshot; 
      git tag snapshot; 
      git push https://$GITHUB_API_KEY@github.com/vzwingma/gestion-budget-communs --tags; 
    else 
      echo "Pas de reTag de snapshot"; 
    fi

deploy:
# Déploiement des releaes sur tag : snapshot ou version 
  - provider: releases
    api-key: $GITHUB_API_KEY
    skip_cleanup: true
    overwrite: true
    file: /home/travis/build/vzwingma/gestion-budget-communs/target/communs-$VERSION.jar
    on:
      repo: vzwingma/gestion-budget-communs
      tags: true