sudo: required

language: java

services:
  - docker
cache:
    directories:
      - $HOME/.m2
git:
  depth: false
install: 
  - mvn clean install -DskipTests=true -B -P openshift

script:
  - echo "Branche Travis : ${TRAVIS_BRANCH}"
  # Tag de snapshot. C'est un tag pour permettre le déploiement sur GitHUB.
  - if [ ${TRAVIS_BRANCH} = "master" ]; then echo "ReTag de snapshot"; git tag -d snapshot; git push https://$GITHUB_API_KEY@github.com/vzwingma/gestion-budget :refs/tags/snapshot; git tag snapshot; git push https://$GITHUB_API_KEY@github.com/vzwingma/gestion-budget --tags; else echo "Pas de reTag de snapshot"; fi
  # Merge sur la branche coverity
  - if [ ${TRAVIS_BRANCH} = "master" ]; then echo "Merge vers la branche Coverity"; git checkout -b coverity_scan origin/coverity_scan; git rebase master; git config --global push.default simple; git push https://$GITHUB_API_KEY@github.com/vzwingma/gestion-budget --set-upstream origin coverity_scan; else echo "Pas de merge vers la branche Coverity"; fi

# Déploiement des releaes sur tag : snapshot ou version 
before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - export TAG=`if [ "$TRAVIS_BRANCH" == "snapshot" ]; then echo "snapshot"; else if [ "$TRAVIS_BRANCH" == v ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi ; fi`
  - echo "Tag=$TAG"
  - cp ~/build/vzwingma/gestion-budget/target/webapps/budget.war ~/build/vzwingma/gestion-budget/src/main/external-ressources/docker/budget.war
  - cd ~/build/vzwingma/gestion-budget/src/main/external-ressources/docker
  - docker build -t vzwingmann/gestion_budget:travis .
  - docker tag vzwingmann/gestion_budget:travis vzwingmann/gestion_budget:$TRAVIS_BRANCH
  - docker push vzwingmann/gestion_budget:$TRAVIS_BRANCH
  - docker tag vzwingmann/gestion_budget:travis vzwingmann/gestion_budget:$TAG  
  - docker push vzwingmann/gestion_budget:$TAG

deploy:
# Déploiement des releaes sur tag : snapshot ou version 
  - provider: releases
    api-key:
      secure: RQZitfoBm2ICLJovBDW1efW9eTHlw668UW8wHJBMEJwh7MkdT9R76Y8Ki1TysiyFy7TIXaavqQ6+StT5QTNB7zajeqrZgRxKYrs7Pumh8E7Kvad13Ee5CAwCASEpb/HHzHW+tL1SHSt+5DrEIZgLM9wWglK0zOtT8RitNpnw/hWf/UM0PXQfgh2MNUlOz6n9KB9TXolD9qdTKV2n/bBWzyoMLno0e3LTUDqtzfm4X/Rd4euoiy04EMHBxDooTNDhw5Vq8RLNC0FcWiz8+GfTb4tc6wt2vzp5OT77Y1WMz6Ysrd+8f4Yeod8+8/kS9NcrUEE4yir8d5OHwGVfbJ91hoMKb2ZXC86pPXQZLKRw50IGql3laI9JT1+slsKc0esmyy6AMIfkSSzLmkNHUv8NzlUJ/Kw0e+cGAkrhks2AzQnGioHxUCNGeRztNfZYqvtaLjibvRZLOZvn802elO9lGuGTo46if3OCscLAtiecWBfy5/kr4ksI3WbVtBmZSuaKK10sjXAvj/Bd9UJj3q1vuOnuT2Fszc7HmRtORPpuLEZyJjBxD9400yG17/uRMGi0d+7zzlLbqOZaHQnKccvq2/2IVW198Y8p/yT+cOQrvdXIc/edNB603BILp8/TA+taF+2iTq+i+fDh9HFPNFwaf0+Dv3NSFQLEYB9eSWaSXG0=
    skip_cleanup: true
    overwrite: true
    file: /home/travis/build/vzwingma/gestion-budget/target/webapps/budget.war
    on:
      repo: vzwingma/gestion-budget
      tags: true