language: java
install: mvn install -DskipTests=true -B -P openshift2
skip_cleanup: true
deploy:
  provider: s3
  bucket: "gestion-budget"
  skip_cleanup: true
  endpoint: s3-website-eu-west-1.amazonaws.com
  region: eu-west-1
  local_dir: target
addons:
  artifacts: true  